spring.application.name=api-gateway
server.port=8020

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-register=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/api-docs/user-service
springdoc.swagger-ui.urls[1].name=Blog Service
springdoc.swagger-ui.urls[1].url=/api-docs/blog-service

